version: "3.6"
services:
  sonarqube:
    image: sonarqube:lts
    ports:
      - 9000:9000
    networks:
      - jenkinsnetwork
    environment:
      - SONARQUBE_HOME=/sonarqube-data
    volumes:
      - /home/ubuntu/sonarqube:/sonarqube-data
  jenkins:
    image: ss-utopia/jenkins
    user: root
    ports:
      - 8080:8080
    networks:
      - jenkinsnetwork
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/jenkins_data:/var/jenkins_home
networks:
  jenkinsnetwork:
